services:
  offchain:
    build:
      context: .
      dockerfile: offchain/Dockerfile
    env_file:
      - offchain/.env
    environment:
      - GRANTS_META_PATH=/app/offchain/data/grants_meta.json
      - IGNORED_GRANT_IDS=b8838eca06631ce81524b5fd55daf17a7c804cbeb5c00d4e4759ed868275c049
    volumes:
      - grants_meta:/app/offchain/data
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    environment:
      - PUBLIC_API_BASE_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.astro
    ports:
      - "4321:4321"
    depends_on:
      - offchain

volumes:
  grants_meta:
