name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  onchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: onchain
    steps:
      - uses: actions/checkout@v4
      - uses: aiken-lang/setup-aiken@v1
        with:
          version: v1.1.23
      - run: aiken check -D

  offchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: offchain
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: offchain
      - run: cargo test
